config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  resources :items  do
    member do
      post :complete
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_type


  validates :name, presence: true
  validates :item_type, presence: true
end

app/models/item_type.rb
class ItemType < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::ActiveRecordStrategy
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  expose(:item)
  
  expose(:incomplete_items) do
    Item.where("completed = ? OR completed IS NULL", false)
  end
  expose(:completed_items) { Item.where(completed: true)}
  def index
  end

  def new
  end

  def create
    item.attributes = item_params

    if item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def complete
    item.completed = true
    item.completed_at = Time.now
    item.save
    redirect_to items_path
  end

  def destroy
    item.destroy
    redirect_to items_path
  end

  private
  def item_params
    params.require(:item).permit(:item_type_id, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/index.html.haml
.container
  %h3 Incompleted Items
  %table.table.table-striped
    - incomplete_items.each do |item|
      %tr
        %td= item.item_type.name
        %td= item.name
        %td
          = link_to("Complete", complete_item_path(item), method: :post, class: 'btn btn-success btn-sm')
          = link_to("Delete", { action: :destroy, id: item.id }, method: :delete, class: 'btn btn-danger btn-sm')
.container
  %h3 Completed Items
  %table.table.table-striped#completed-table
    %tr
      %th Type
      %th Name
      %th Completed At
    - completed_items.each do |item|
      %tr
        %td= item.item_type.name
        %td= item.name
        %td= item.completed_at.strftime("%b %d, %Y %H:%M")

app/views/items/new.html.haml
.col-md-3
  %h2 New Item
  - if item.errors.messages.any?
    - item.errors.messages.each do |field,message|
      = field.to_s.humanize + ': ' + message.join(', ')
      %br
  = form_for item do |f|
    .form-group
      = f.label :item_type_id
      %br
      = f.select :item_type_id, options_for_select(ItemType.all.collect { |item_type| [item_type.name, item_type.id]}), {}, class: 'form-control'
    .form-group
      = f.label :name
      %br
      = f.text_field :name, class: 'form-control'
    %br
    = f.submit 'Create item', class: 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TodoApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default{:role => "navigation"}
      .container-fluid
        .navbar-header
          %a.navbar-brand{:href => root_path} Todo App
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              = link_to 'Items', items_path
            %li
              = link_to 'Create item', new_item_path
    = yield